name: todo_app
description: A new Flutter project for Todo App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.1 # En güncel kararlı sürüm
  http: ^1.1.0
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  flutter_dotenv: ^5.1.0
  flutter_local_notifications: ^17.0.0 # Daha kararlı sürüm (20.0 bazen beta uyuşmazlığı yapabilir)
  
  # --- EKSİK OLAN VE ÖNEMLİ PAKETLER ---
  timezone: ^0.9.2          # Bildirimlerin zamanlanması (Reminder) için zorunlu
  flutter_native_timezone: ^2.0.0 # Kullanıcının yerel saat dilimini otomatik algılamak için
  path_provider: ^2.1.1     # Dosya yolları yönetimi için

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - .env